#ifndef _CFORMAT_
#define _CFORMAT_


#define ERR_SUCCESS 0
#define ERR_OUT_OF_MEMORY 1
#define ERR_INVALID_PARAMETER 2
#define ERR_FILE_OPEN 3
#define ERR_FILE_READ 4
#define ERR_INVALID_HEADER_FILE 5
#define ERR_INVALID_MAGIC_NUMBER 6


#endif //_CFORMAT_